# docker-compose.yml

networks:
  redeasterisk:
    driver: bridge

services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    container_name: asterisk
    networks:
      - redeasterisk
    ports:
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"
    volumes:
      - ./asterisk-configs:/etc/asterisk # Monta a pasta de configuração local
    restart: unless-stopped
    stdin_open: true  # CORRIGIDO: de 'stdin: true' para 'stdin_open: true'
    tty: true
    command: /bin/bash

  linphone_pedro:
    build:
      context: .
      dockerfile: Dockerfile.linphone
    container_name: linphone_pedro
    networks:
      - redeasterisk
    environment:
      - SIP_USER=pedro
      - SIP_PASS=1234
      - TARGET_DIAL=true # Pedro vai iniciar a chamada
      - TARGET_EXTENSION=0800
    depends_on:
      - asterisk
    tty: true # Mantém o stdin aberto para linphonec
    stdin_open: true # Mantém o stdin aberto para linphonec
    restart: unless-stopped

  linphone_maria:
    build:
      context: .
      dockerfile: Dockerfile.linphone
    container_name: linphone_maria
    networks:
      - redeasterisk
    environment:
      - SIP_USER=maria
      - SIP_PASS=1234
      - AUTO_ANSWER=true # Maria vai atender automaticamente
    depends_on:
      - asterisk
    tty: true
    stdin_open: true
    restart: unless-stopped
